name: Build & Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: echo "SITE_URL=https://sunderee.github.io/sunderee-blog" > .env
      - name: Add Torchlight.dev token
        run: echo "TORCHLIGHT_TOKEN=${{ secrets.TORCHLIGHT_TOKEN }}" >> .env
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Built the site
        run: php hyde build --no-interaction
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"
      - name: Empty site directory
        run: rm -rf *
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: "."
      - name: Create .nojekyll file
        run: touch .nojekyll
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Upload compiled site ${{ github.sha }}"
